disable deploys for some apps

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -35,6 +35,16 @@ jobs:
     concurrency:
       group: deploy-${{ inputs.env }}
     steps:
+      - name: Check if deployment is disabled
+        run: |
+          if [[ "${{ inputs.app }}" == "queue" || "${{ inputs.app }}" == "esapi" ]]; then
+            echo "Deployment is disabled for app: ${{ inputs.app }}. Ask Jim to deploy manually."
+            echo "::error::Deployment is disabled for app: ${{ inputs.app }}. Ask Jim to deploy manually see job logs for instructions."
+            echo "The deploy script is undergoing maintenance and is not tested for ${{ inputs.app }}."
+            exit 1
+          fi
+
+      
       - name: Set up Docker Buildx
         id: buildx
         uses: docker/setup-buildx-action@v3
